name: test

on:
  schedule:
    # Runs at 2 AM UTC every Monday
    - cron: '0 2 * * 1'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  AWS_ROLE: arn:aws:iam::270074865685:role/terraform-module-ci-test
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  NIX_INSTALL_SHA: 1ef3dd0d3797b19bb2919a8d7cffe121af4cfb517008d82b67bdadc31ec87544
  NIX_INSTALL_VERSION: 2.34.5

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      # https://github.com/aws-actions/configure-aws-credentials/releases
      - uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: ${{env.AWS_ROLE}}
          role-session-name: ${{github.run_id}}
          aws-region: ${{env.AWS_REGION}}
          role-duration-seconds: 14400 # 4 hours
      - name: install-nix
        run: |
          curl -L -o install.sh "https://releases.nixos.org/nix/nix-${NIX_INSTALL_VERSION}/install"
          echo "${NIX_INSTALL_SHA} install.sh" | sha256sum -c -
          chmod +x install.sh
          ./install.sh
          source /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix --version
          which nix
      # https://github.com/actions/checkout/releases
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: steps.release-please.outputs.pr
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          fetch-depth: 0
      - name: Run Tests
        shell: 'nix develop --ignore-environment --extra-experimental-features nix-command --extra-experimental-features flakes --keep HOME --keep SSH_AUTH_SOCK --keep IDENTIFIER --keep GITHUB_TOKEN --keep GITHUB_OWNER --keep ZONE --keep AWS_ROLE --keep AWS_REGION --keep AWS_DEFAULT_REGION --keep AWS_ACCESS_KEY_ID --keep AWS_SECRET_ACCESS_KEY --keep AWS_SESSION_TOKEN --keep UPDATECLI_GPGTOKEN --keep UPDATECLI_GITHUB_TOKEN --keep UPDATECLI_GITHUB_ACTOR --keep GPG_SIGNING_KEY --keep NIX_ENV_LOADED --keep TERM --keep CI --command bash -e {0}'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_OWNER: rancher
          IDENTIFIER: ${{github.run_id}}
          ZONE: ${{secrets.ZONE}}
          CI: "true"
        run: |
          export GITHUB_TOKEN
          export GITHUB_OWNER
          export IDENTIFIER
          export ZONE
          export CI
          ./run_tests.sh
