name: test

on:
  schedule:
    # Runs at 2 AM UTC every Monday
    - cron: '0 2 * * 1'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  AWS_ROLE: arn:aws:iam::270074865685:role/terraform-module-ci-test
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: {}

jobs:
  test:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
      volumes: # these are mounted only for the purpose of clearing them out so the runner doesn't run out of storage space
        - /usr/share/dotnet:/host_dotnet
        - /usr/local/lib/android:/host_android
        - /opt/ghc:/host_ghc
        - /opt/hostedtoolcache:/host_toolcache
        - /usr/local/.ghcup:/host_ghcup
        - /usr/local/share/boost:/host_boost
    timeout-minutes: 60
    steps:
      - name: 'Checkout'
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: 'Free Disk Space'
        run: |
          bash .github/workflows/scripts/free-disk-space.sh

      - name: 'Configure AWS Credentials'
        # https://github.com/aws-actions/configure-aws-credentials/releases
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{env.AWS_ROLE}}
          role-session-name: ${{github.run_id}}
          aws-region: ${{env.AWS_REGION}}
          role-duration-seconds: 14400 # 4 hours

      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_OWNER: rancher
          IDENTIFIER: ${{github.run_id}}
          ZONE: ${{secrets.ZONE}}
        run: |
          bash .github/workflows/scripts/nix-run.sh bash .github/workflows/scripts/execute-tests.sh
