name: Update Go Dependencies

on:
  schedule:
    - cron: '0 4 * * 1' # Every Monday at 04:00
  workflow_dispatch:

jobs:
  update-go-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go
        # https://github.com/actions/setup-go/releases
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '1.x'
          check-latest: true

      - name: Update Go version and dependencies
        id: update-deps
        working-directory: test
        run: ${{ github.workspace }}/.github/workflows/scripts/update-go-deps.sh

      - name: Create Verified Pull Request
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const { default: script } = await import('${{ github.workspace }}/.github/workflows/scripts/create-verified-pr.js');
            await script({
              github,
              context,
              exec: (await import('@actions/exec')).exec,
              core: await import('@actions/core')
            });
